# Generated by Django 4.1.4 on 2022-12-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='current_url',
            field=models.DateTimeField(),
        ),
    ]
