# Generated by Django 4.1.4 on 2022-12-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensummary',
            name='chat_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
