# Generated by Django 4.1.4 on 2022-12-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_tokensummary_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensummary',
            name='chat_id',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
