# Generated by Django 4.1.4 on 2022-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_tokensummary_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
