# Generated by Django 4.1.4 on 2022-12-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_visit_current_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='time',
            new_name='current_time',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='today',
        ),
    ]
