# Generated by Django 4.1.4 on 2022-12-12 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_visitcount_remove_track_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcount',
            name='today_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitcount',
            name='today',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
    ]
