# Generated by Django 4.1.4 on 2022-12-12 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_dailyvisit_monthlyvisit_track_visit_yearlyvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
    ]
