# Generated by Django 4.1.4 on 2022-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='last_visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
