# Generated by Django 4.1.4 on 2022-12-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_visit_last_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='last_visit_date',
        ),
    ]
