# Generated by Django 4.1.4 on 2022-12-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_remove_visit_last_visit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='today',
        ),
    ]
