# Generated by Django 4.1.4 on 2022-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_rename_date_visit_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='total_count',
        ),
        migrations.AddField(
            model_name='visit',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
