# Generated by Django 4.1.4 on 2022-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_remove_track_total_count_visit_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='daily_visits',
            field=models.ManyToManyField(to='location.dailyvisit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='monthly_visits',
            field=models.ManyToManyField(to='location.monthlyvisit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='yearly_visits',
            field=models.ManyToManyField(to='location.yearlyvisit'),
        ),
    ]
