# Generated by Django 4.1.4 on 2022-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_alter_dailyvisit_today_alter_monthlyvisit_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyvisit',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yearlyvisit',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
