# Generated by Django 4.1.4 on 2022-12-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_alter_monthlyvisit_visits_alter_yearlyvisit_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisit',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
