# Generated by Django 4.1.3 on 2022-12-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_dailyvisit_visits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyvisit',
            old_name='visits',
            new_name='d_visits',
        ),
    ]
