# Generated by Django 4.1.3 on 2022-12-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_rename_visits_dailyvisit_d_visits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyvisit',
            old_name='d_visits',
            new_name='visits',
        ),
    ]
