# Generated by Django 4.1.4 on 2022-12-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_rename_d_visits_dailyvisit_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='daily_visits',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='monthly_visits',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='yearly_visits',
        ),
    ]
