# Generated by Django 4.1.4 on 2022-12-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_remove_visit_daily_visits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvisit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='monthlyvisit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='yearlyvisit',
            name='author',
        ),
    ]
