# Generated by Django 4.1.4 on 2022-12-26 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_visitcount_remove_track_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('link_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tokensummary',
            name='token_count',
        ),
        migrations.AlterField(
            model_name='visitcount',
            name='last_visit_date',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
        migrations.AlterField(
            model_name='visitcount',
            name='today',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
    ]
