# Generated by Django 4.1.4 on 2022-12-26 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_remove_linkvisit_user_id_alter_linkvisit_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkvisit',
            name='count',
        ),
        migrations.RemoveField(
            model_name='linkvisit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='linkvisit',
            name='link_id',
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='daily_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='monthly_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='yearly_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkvisit',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkvisit',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
