# Generated by Django 4.1.4 on 2022-12-26 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0025_remove_linkvisit_count_remove_linkvisit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkvisit',
            name='daily_count',
        ),
        migrations.RemoveField(
            model_name='linkvisit',
            name='link',
        ),
        migrations.RemoveField(
            model_name='linkvisit',
            name='monthly_count',
        ),
        migrations.RemoveField(
            model_name='linkvisit',
            name='yearly_count',
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='link_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkvisit',
            name='month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkvisit',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
