# Generated by Django 4.1.4 on 2022-12-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_remove_linkvisit_daily_count_remove_linkvisit_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkVisit',
        ),
    ]
