# Generated by Django 4.1.4 on 2022-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0027_delete_linkvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitcount',
            name='today',
        ),
    ]
