# Generated by Django 4.1.4 on 2022-12-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_contactformdata_alter_visitcount_last_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensummary',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
